### PR TITLE
ACAS-774: Update Dockerfile to CentOS Stream 9 and Python 3.11

### PR DESCRIPTION
**Pull request by brianbolt**
## Description
 - Centos8 stream is eol and producing errors like this https://github.com/mcneilco/acas/actions/runs/9372934771/job/25805634813?pr=1162
 
```
#5 [ 2/19] RUN   dnf update -y &&   dnf upgrade -y &&   dnf install -y tar git &&   dnf install -y fontconfig urw-fonts iputils postgresql &&   dnf clean all
#5 0.289 CentOS Stream 8 - AppStream                     864  B/s |  38  B     00:00    
#5 0.294 Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
#5 ERROR: process "/bin/sh -c dnf update -y &&   dnf upgrade -y &&   dnf install -y tar git &&   dnf install -y fontconfig urw-fonts iputils postgresql &&   dnf clean all" did not complete successfully: exit code: 1
```

 - This fix upgrades to centos stream8 and python3.11 (from old python3.6)

## Related Issue
ACAS-744

## How Has This Been Tested?
I let the acasclient tests run but did 0 testing of the front end or other features.  The acasclient tests do not cover any python running inside the acas container which was upgraded.  This would affect the integration with LiveDesign and should be tested but I'm inclined to leave that to QA to test.

### CODE REVIEW

**Review by bffrost — COMMENTED** [review]
@brianbolt makes sense, and seems OK to me to leave the integration testing to QA.
I see this is targeted for release/2024.3.x . While we'd like to put OS upgrades in general into later releases (as they're inherently more risky), as I understand it this issue will block us from doing any new builds of any current release.

Do we want to consider targeting an earlier release of ACAS for this fix?

**Comment by brianbolt** [comment]
> @brianbolt makes sense, and seems OK to me to leave the integration testing to QA. I see this is targeted for release/2024.3.x . While we'd like to put OS upgrades in general into later releases (as they're inherently more risky), as I understand it this issue will block us from doing any new builds of any current release.
> 
> Do we want to consider targeting an earlier release of ACAS for this fix?

Thanks, yes, I just updated the base branch. I branched from 2024.1.x but forgot to set it as the base on the PR.

**Review by tanay-makharia — APPROVED** [review]
LGTM

**Review by bffrost — APPROVED** [review]

**Comment by brianbolt** [comment]
Changed base branch to [release/2024.3.x](https://github.com/mcneilco/acas/tree/release/2024.3.x) because I found a workaround to continue to use stream8 for 2024.1.x and 2024.2.x https://github.com/mcneilco/acas/pull/1166

**Comment by bffrost** [comment]
LGTM with the new base branch as per our conversation earlier today.

**Pull request merged**
