### PR TITLE
ACAS-646: Update CmpdReg bulkloader picklists to be type ahead (PicklistSelect2Controller) picklists.

### PR DESCRIPTION
**Pull request by brianbolt**
## Description
 - Changed CmpdReg BulkLoader PicklistController to PicklistSelect2Controllers
 - Updating the styling of errors, widths...etc. in the CSS

## Related Issue
ACAS-646

## How Has This Been Tested?
 - Validated and Registered compounds
 - Used the type ahead to narrow list and make selections (see screenshot below)

Screenshot 2023-04-05 at 3 30 38 PM

 - Verified each of the pick lists rendered the correct Red colors (see screenshot below) when in error states

Screenshot 2023-04-05 at 3 30 30 PM

### CODE REVIEW

**Comment by brianbolt** [comment]
Here is a screenshot of the original (non type ahead select lists)

Screenshot 2023-04-05 at 3 38 45 PM

**Review by dalejerikson — APPROVED** [review]
👍 LGTM

**Review by hhan-schrodinger — APPROVED** [review]
Looks good to me, didn't know about the PickListSelect2Controllers before (seems handy)!

**Review by hweissig — APPROVED** [review]
Love it when a simple switch of gadgets makes things much easier for the end user.

LGTM!

**Pull request merged**
