### PR TITLE
ACAS 524: Fix SEL "Next" button being off the screen to the right

### PR DESCRIPTION
**Pull request by bffrost**
## Description
- Tweaked the module width of `.bv_outerContainer` which is found only in BasicFileValidateAndSave

### Before
Wide
Screen Shot 2022-11-18 at 9 16 06 AM

Medium
Screen Shot 2022-11-18 at 9 16 14 AM

### After
Wide
Screen Shot 2022-11-18 at 9 12 34 AM

Medium
Screen Shot 2022-11-18 at 9 12 20 AM

Narrow
Screen Shot 2022-11-18 at 9 12 26 AM

Very Narrow
Screen Shot 2022-11-18 at 9 14 37 AM

Narrowest
Screen Shot 2022-11-18 at 9 14 45 AM

## How Has This Been Tested?
Local testing with different window widths.

### CODE REVIEW

**Comment by bffrost** [comment]
@brianbolt Thanks for the note. There was an issue with dose response previews. I've expanded it out further to 95%. I found that 100% cuts off the Next Button, but 95% still cleanly shows it, and scales down better to smaller windows.
On my 16 inch MacBook Pro screen:
Full width: Next button is visible:
Screen Shot 2022-11-23 at 8 52 18 AM

Half width: Next button still visible:
Screen Shot 2022-11-23 at 8 52 09 AM

Full width: Dose Response validation summary just barely fits
Screen Shot 2022-11-23 at 8 52 34 AM

Half width: Dose Response validation summary goes off the screen to the right
Screen Shot 2022-11-23 at 8 52 43 AM

Screen Shot 2022-11-23 at 8 52 51 AM

**Review by hhan-schrodinger — APPROVED** [review]
LGTM! Do you think there should be a ticket down the line to prevent the main panel from covering the navigation panel on the left?

**Review by brianbolt — APPROVED** [review]
LGTM

**Comment by bffrost** [comment]
Thanks @hhan-schrodinger . I've filed ACAS-527 for that.

**Pull request merged**
